# action.yml
name: "Giessdenkiez.de OSM Pumps Harvester"
description: "Aggregates data from Open Street Maps to build a geojson"
inputs:
  outfile-path: # id of input
    description: "Where to write the data"
    required: true
    default: "public/data/pumps.geojson"
  query:
    description: "Query that is used to retrieve pumps data from OSM. If omitted Berlin pumps are retrieved."
    required: false
outputs:
  file: # id of output
    description: "the generated file path"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.outfile-path }}
    - -q ${{ inputs.query }}
